### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by jakekall** [vuorenkoski/sudoku-solver#1]
Ladattu 13.06.2020 01:10

Ohjelma näyttää oikein hyvältä. Kaikki toimi ja testit meni läpi. Koodi on mielestäni selkeää ja kommentteja löytyy mukavasti.

Oikeastaan mitään ihmeellisempiä parannusehdotuksia ei minulla ole. Jonkinlaisen käyttöliittymän voisi tehdä, mutta se olikin jo kirjattu viikkoraporttiin.

**Comment by vuorenkoski** [comment]
Käyttöliittymä tehty.
